name: Node Setup

inputs:
  node_version:
    description: 'The Node.js version to use'
    required: true

runs:
  using: 'composite'
  steps:
    # Set up Node.js and Yarn
    - name: Set up Node/Yarn
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'

    # Install JavaScript dependencies if yarn.lock exists
    - name: Install JS deps (if any)
      if: hashFiles('yarn.lock') != ''
      run: yarn install --frozen-lockfile
      shell: bash
