version: '3'
services:
  db:
    # ビルド済みのイメージを使用
    image: mysql:8.0
    # 環境変数
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # ホストマシンとコンテナ間のファイル共有
    volumes:
      - ./tmp/db:/var/lib/mysql
    # ホストマシンとコンテナ間で使用するポートのマッピング
    ports:
      - '3306:3306'

  app:
    # Dockerfileからイメージをビルド
    build: .
    # コンテナ起動時に実行するコマンドを上書き
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    # ホストマシンとコンテナ間のファイル共有
    volumes:
      - '.:/app'
    # ホストマシンとコンテナ間で使用するポートのマッピング
    ports:
      - '3000:3000'
    # サービスの依存関係と起動順
    depends_on:
      - db
      - selenium
    environment:
      # 接続情報を環境変数にセット（接続先はdatabase.yml）
      MYSQL_USER: ${MYSQL_USER}
      # FIXME: MYSQL_ROOT_PASSWORDを使わないと何故かdbに接続できない
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # CapybaraがSeleniumに接続するためのホスト名
      SELENIUM_HOST: selenium
      # Railsのテスト環境を指定
      RAILS_ENV: test

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - '4444:4444' # Seleniumのデフォルトポート
