name: Ruby Setup

inputs:
  ruby_version:
    description: "The Ruby version to use"
    required: true

runs:
  using: "composite"
  steps:
      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby_version }}  # fileで.ruby-versionを指定すると認識されなかった
          bundler-cache: true                       # vendor/bundleを自動的にキャッシュ
