name: CI

on:
  push:
    # 全てのブランチでCIを走らせたい場合はbranchesを削除
    branches: [ main, develop, "feature/**", "refactor/**" ]
  pull_request:

env:
  RAILS_ENV: test
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}

jobs:
  # ---- Lint ----
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ./.github/actions/setup-ruby
        with:
          ruby_version: 2.6.3

      - name: RuboCop
        run: |
          bundle exec rubocop --format progress

      - name: ERB Lint
        if: hashFiles('**/*.erb') != ''
        run: |
          bundle exec erblint --lint-all --format compact

  # ---- Security ----
  security:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ./.github/actions/setup-ruby
        with:
          ruby_version: 2.6.3

      # SAST
      - name: Brakeman  # 警告レベル2以上（Medium）
        run: |
          bundle exec brakeman -q -w2 || true

      - name: Bundler Audit
        run: |
          bundle exec bundler-audit check --update || true

  # ---- Smoke Tests ----
  smoke:
    needs: lint
    runs-on: ubuntu-latest
    environment: rails_todo
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ./.github/actions/setup-ruby
        with:
          ruby_version: 2.6.3

      - name: Set up Node/Yarn
        uses: ./.github/actions/setup-node
        with:
          node_version: 16
      
      # Check routes and boot
      - name: Smoke (routes & boot)
        run: |
          bin/rails routes >/dev/null
          bin/rails runner 'puts "Boot OK"'

  # ---- Tests ----
  tests:
    needs: lint
    runs-on: ubuntu-latest
    environment: rails_todo
    timeout-minutes: 15

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_NAME_TEST }}
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -ppassword"
          --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ./.github/actions/setup-ruby
        with:
          ruby_version: 2.6.3

      - name: Set up Node/Yarn
        uses: ./.github/actions/setup-node
        with:
          node_version: 16

      - name: Prepare Database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:prepare

      - name: Run RSpec
        if: ${{ hashFiles('spec/**/*') != '' }}
        run: bundle exec rspec --format progress --force-color

      - name: Run Minitest
        if: ${{ hashFiles('test/**/*') != '' }}
        env:
          DISABLE_SPRING: 1 # CIでは必要ないので無効化
        run: bin/rails test
