name: CI

on:
  push:
    # 全てのブランチでCIを走らせたい場合はbranchesを削除
    branches: [ main, develop, "feature/**", "refactor/**" ]
  pull_request:

env:
  RAILS_ENV: test
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}

jobs:
  # ---- Lint ----
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ./.github/workflows/setup-ruby.yml
        with:
          ruby_version: 2.6.3

      - name: RuboCop
        run: |
          bundle exec rubocop --format progress

      - name: ERB Lint
        if: hashFiles('**/*.erb') != ''
        run: |
          bundle exec erblint --lint-all --format compact

  # ---- Security ----
  security:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ./.github/workflows/setup-ruby.yml
        with:
          ruby_version: 2.6.3

      # SAST
      - name: Brakeman  # 警告レベル2以上（Medium）
        run: |
          bundle exec brakeman -q -w2 || true

      - name: Bundler Audit
        run: |
          bundle exec bundler-audit check --update || true

  # ---- Database ----
  database:
    needs: lint
    runs-on: ubuntu-latest
    environment: rails_todo
    timeout-minutes: 15
    uses: ./.github/workflows/mysql-service.yml
    with:
      mysql_root_password: password
      mysql_database: app_test

  # ---- Smoke Tests ----
  smoke:
    needs: database
    runs-on: ubuntu-latest
    environment: rails_todo
    timeout-minutes: 15
    uses: ./.github/workflows/setup-ci-env.yml
    with:
      ruby_version: 2.6.3
      node_version: 16  # 安定版
      mysql_root_password: password
      mysql_database: app_test

    steps:
      # Check routes and boot
      - name: Smoke (routes & boot)
        run: |
          bin/rails routes >/dev/null
          bin/rails runner 'puts "Boot OK"'

  # ---- Tests ----
  tests:
    needs: database
    runs-on: ubuntu-latest
    environment: rails_todo
    timeout-minutes: 15
    uses: ./.github/workflows/setup-ci-env.yml
    with:
      ruby_version: 2.6.3
      node_version: 16 # 安定版
      mysql_root_password: password
      mysql_database: app_test

    steps:
      - name: Run RSpec
        if: ${{ hashFiles('spec/**/*') != '' }}
        run: bundle exec rspec --format progress --force-color

      - name: Run Minitest
        if: ${{ hashFiles('test/**/*') != '' }}
        env:
          DISABLE_SPRING: 1 # CIでは必要ないので無効化
        run: bin/rails test
