name: DB Prepare

on:
  workflow_call:
    inputs:
      mysql_root_password:
        description: "The root password for MySQL"
        required: true
        type: string
      mysql_database:
        description: "The database name to create"
        required: true
        type: string

jobs:
  setup-database:
    needs: setup-mysql
    uses: ./.github/workflows/setup-mysql.yml
    with:
      mysql_root_password: ${{ inputs.mysql_root_password }}
      mysql_database: ${{ inputs.mysql_database }}

  prepare-database:
    runs-on: ubuntu-latest
    needs: setup-database
    steps:
      - name: Prepare Database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:prepare
