name: MySQL Service Setup

on:
  workflow_call:
    inputs:
      mysql_root_password:
        description: "The root password for MySQL"
        required: true
        type: string
      mysql_database:
        description: "The database name to create"
        required: true
        type: string

jobs:
  setup-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ inputs.mysql_root_password }}
          MYSQL_DATABASE: ${{ inputs.mysql_database }}
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -ppassword"
          --health-interval=10s --health-timeout=5s --health-retries=10
