name: CI Environment Setup

on:
  workflow_call:
    inputs:
      ruby_version:
        description: "The Ruby version to use"
        required: true
        type: string
      node_version:
        description: "The Node.js version to use"
        required: true
        type: string
      mysql_root_password:
        description: "The root password for MySQL"
        required: true
        type: string
      mysql_database:
        description: "The database name to create"
        required: true
        type: string

jobs:
  setup-ruby:
    uses: ./.github/workflows/setup-ruby.yml
    with:
      ruby_version: ${{ inputs.ruby_version }}

  setup-node:
    runs-on: ubuntu-latest
    needs: setup-ruby
    steps:
      # Set up Node.js and Yarn
      - name: Set up Node/Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'yarn'

      # Install JavaScript dependencies if yarn.lock exists
      - name: Install JS deps (if any)
        if: hashFiles('yarn.lock') != ''
        run: yarn install --frozen-lockfile

  setup-database:
    needs: setup-ruby
    uses: ./.github/workflows/mysql-service.yml
    with:
      mysql_root_password: ${{ inputs.mysql_root_password }}
      mysql_database: ${{ inputs.mysql_database }}
